version: "3"
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - APP_ENV=dev 
      - DB_URL="mongodb://mongo/tdhack" 
    networks:
      place:
        aliases:
          - api
    depends_on:
      - mongo
    volumes:
      - ./backend:/usr/src/app
    command: npm run start:dev
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6479:6379
    networks:
      place:
        aliases:
          - redis
  mongo-express:
     image: mongo-express
     restart: always
     networks:
       place:
        aliases:
         - express
     ports:
       - 8081:8081
  mongo:
    image: mongo:4.4
    restart: always
    volumes:
      - ./data/db:/data/db
      - ./tools/import:/data/import
    ports:
      - 28017:27017 
    networks:
      place:
        aliases:
          - mongo
volumes:
  data-volume:
#### network config
networks:
  place:
