version: "3"
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - APP_ENV=dev
      - APP_URL=http://localhost:4214
      - APP_HOST=localhost
      - WEBTOKEN_SECRET_KEY=uAsBwuAsBw6WxqD6WxqDuAsBw6WxqDuAsBw6WxqD
      - WEBTOKEN_EXPIRATION_TIME=240000
      - DB_URL="mongodb://mongo/anoya"
      - MAILGUN_DOMAIN="smtp.gmail.com"
      - MAILGUN_HOST="465"
      - MAILGUN_KEY="pass"
      - MAILGUN_FROM="Amazing site!"
    networks:
      place:
        aliases:
          - api
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
         - 6479:6379
    networks:
      place:
        aliases:
          - redis
  mongo-express:
     image: mongo-express
     restart: always
     networks:
       place:
        aliases:
         - express
     ports:
       - 8081:8081
  mongo:
    image: mongo:4.4
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - 28017:27017 
    networks:
      place:
        aliases:
          - mongo
volumes:
  data-volume:
#### network config
networks:
  place:
